services:
  frontend:
    profiles: [frontend]
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: production
    image: ${COMPOSE_PROJECT_NAME}-frontend:production
    volumes:
      - type: bind
        source: ./src/frontend
        target: /app
    working_dir: /app
    tty: true
    user: 'node'
    networks:
      - frontend

networks:
  frontend:
    name: ${COMPOSE_PROJECT_NAME}-frontend
    driver: bridge
