#!/bin/sh
set -eu

: "${MONITORING_POSTGRES_PASSWORD:?Set SERVICE_MONITORING_POSTGRES_PASSWORD in the root .env}"
: "${MONITORING_GRAFANA_PASSWORD:?Set SERVICE_MONITORING_GRAFANA_ADMIN_PASSWORD in the root .env}"
